# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Jun 14 16:26:30 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Szyfrowanie = QtWidgets.QTabWidget(self.centralwidget)
        self.Szyfrowanie.setGeometry(QtCore.QRect(10, 20, 441, 511))
        self.Szyfrowanie.setObjectName("Szyfrowanie")
        self.tabDropbox = QtWidgets.QWidget()
        self.tabDropbox.setObjectName("tabDropbox")
        self.groupBox = QtWidgets.QGroupBox(self.tabDropbox)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 251, 181))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 160, 102))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabDropbox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 240, 251, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 20, 191, 99))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelKlucz = QtWidgets.QLabel(self.layoutWidget)
        self.labelKlucz.setObjectName("labelKlucz")
        self.horizontalLayout_5.addWidget(self.labelKlucz)
        self.lineEditKlucz = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKlucz.setObjectName("lineEditKlucz")
        self.horizontalLayout_5.addWidget(self.lineEditKlucz)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.spinBoxOdswiez = QtWidgets.QSpinBox(self.tabDropbox)
        self.spinBoxOdswiez.setGeometry(QtCore.QRect(370, 450, 42, 22))
        self.spinBoxOdswiez.setMaximum(120)
        self.spinBoxOdswiez.setProperty("value", 5)
        self.spinBoxOdswiez.setObjectName("spinBoxOdswiez")
        self.label_2 = QtWidgets.QLabel(self.tabDropbox)
        self.label_2.setGeometry(QtCore.QRect(300, 440, 71, 41))
        self.label_2.setObjectName("label_2")
        self.Szyfrowanie.addTab(self.tabDropbox, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(29, 19, 381, 421))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeView = QtWidgets.QTreeView(self.verticalLayoutWidget_2)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.AESGeneruj = QtWidgets.QPushButton(self.tab_2)
        self.AESGeneruj.setGeometry(QtCore.QRect(29, 450, 75, 23))
        self.AESGeneruj.setObjectName("AESGeneruj")
        self.KluczAES_line = QtWidgets.QLineEdit(self.tab_2)
        self.KluczAES_line.setGeometry(QtCore.QRect(110, 450, 151, 20))
        self.KluczAES_line.setObjectName("KluczAES_line")
        self.Szyfrowanie.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.email_box = QtWidgets.QGroupBox(self.tab)
        self.email_box.setGeometry(QtCore.QRect(10, 10, 421, 211))
        self.email_box.setObjectName("email_box")
        self.email_nadawca = QtWidgets.QLineEdit(self.email_box)
        self.email_nadawca.setGeometry(QtCore.QRect(100, 20, 311, 20))
        self.email_nadawca.setObjectName("email_nadawca")
        self.email_adresat = QtWidgets.QLineEdit(self.email_box)
        self.email_adresat.setGeometry(QtCore.QRect(100, 80, 311, 20))
        self.email_adresat.setObjectName("email_adresat")
        self.email_haslo = QtWidgets.QLineEdit(self.email_box)
        self.email_haslo.setGeometry(QtCore.QRect(100, 50, 311, 20))
        self.email_haslo.setInputMethodHints(QtCore.Qt.ImhNone)
        self.email_haslo.setInputMask("")
        self.email_haslo.setObjectName("email_haslo")
        self.label_nadawca = QtWidgets.QLabel(self.email_box)
        self.label_nadawca.setGeometry(QtCore.QRect(10, 20, 81, 20))
        self.label_nadawca.setObjectName("label_nadawca")
        self.label_haslo = QtWidgets.QLabel(self.email_box)
        self.label_haslo.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.label_haslo.setObjectName("label_haslo")
        self.label_adresat = QtWidgets.QLabel(self.email_box)
        self.label_adresat.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.label_adresat.setObjectName("label_adresat")
        self.emailWyslij = QtWidgets.QPushButton(self.email_box)
        self.emailWyslij.setGeometry(QtCore.QRect(200, 150, 75, 23))
        self.emailWyslij.setObjectName("emailWyslij")
        self.email_klucz = QtWidgets.QLineEdit(self.email_box)
        self.email_klucz.setGeometry(QtCore.QRect(100, 110, 311, 20))
        self.email_klucz.setObjectName("email_klucz")
        self.label_klucz = QtWidgets.QLabel(self.email_box)
        self.label_klucz.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.label_klucz.setObjectName("label_klucz")
        self.protokoly_box = QtWidgets.QGroupBox(self.email_box)
        self.protokoly_box.setGeometry(QtCore.QRect(10, 140, 151, 61))
        self.protokoly_box.setFlat(False)
        self.protokoly_box.setCheckable(False)
        self.protokoly_box.setObjectName("protokoly_box")
        self.SSL_radio = QtWidgets.QRadioButton(self.protokoly_box)
        self.SSL_radio.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.SSL_radio.setObjectName("SSL_radio")
        self.TSL_radio = QtWidgets.QRadioButton(self.protokoly_box)
        self.TSL_radio.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.TSL_radio.setObjectName("TSL_radio")
        self.emailRSAGeneruj = QtWidgets.QPushButton(self.email_box)
        self.emailRSAGeneruj.setGeometry(QtCore.QRect(310, 150, 81, 23))
        self.emailRSAGeneruj.setObjectName("emailRSAGeneruj")
        self.aesWyslij = QtWidgets.QPushButton(self.email_box)
        self.aesWyslij.setGeometry(QtCore.QRect(200, 180, 75, 23))
        self.aesWyslij.setObjectName("aesWyslij")
        self.niezaszyfrowanyRSA = QtWidgets.QLineEdit(self.tab)
        self.niezaszyfrowanyRSA.setGeometry(QtCore.QRect(10, 230, 191, 21))
        self.niezaszyfrowanyRSA.setObjectName("niezaszyfrowanyRSA")
        self.szyfrujRSA = QtWidgets.QPushButton(self.tab)
        self.szyfrujRSA.setGeometry(QtCore.QRect(10, 260, 75, 23))
        self.szyfrujRSA.setObjectName("szyfrujRSA")
        self.deszyfrujRSA = QtWidgets.QPushButton(self.tab)
        self.deszyfrujRSA.setGeometry(QtCore.QRect(120, 260, 81, 23))
        self.deszyfrujRSA.setObjectName("deszyfrujRSA")
        self.nazwaUzytkownikaLine = QtWidgets.QLineEdit(self.tab)
        self.nazwaUzytkownikaLine.setGeometry(QtCore.QRect(10, 290, 191, 21))
        self.nazwaUzytkownikaLine.setObjectName("nazwaUzytkownikaLine")
        self.Szyfrowanie.addTab(self.tab, "")
        self.tab_szyfrowanie = QtWidgets.QWidget()
        self.tab_szyfrowanie.setObjectName("tab_szyfrowanie")
        self.nazwaPliku_szyfrowanie = QtWidgets.QLineEdit(self.tab_szyfrowanie)
        self.nazwaPliku_szyfrowanie.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.nazwaPliku_szyfrowanie.setObjectName("nazwaPliku_szyfrowanie")
        self.szyfrowanieAES_button = QtWidgets.QPushButton(self.tab_szyfrowanie)
        self.szyfrowanieAES_button.setGeometry(QtCore.QRect(10, 40, 75, 23))
        self.szyfrowanieAES_button.setObjectName("szyfrowanieAES_button")
        self.nazwaPliku_deszyfrowanie = QtWidgets.QLineEdit(self.tab_szyfrowanie)
        self.nazwaPliku_deszyfrowanie.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.nazwaPliku_deszyfrowanie.setObjectName("nazwaPliku_deszyfrowanie")
        self.deszyfrowanieAES_button = QtWidgets.QPushButton(self.tab_szyfrowanie)
        self.deszyfrowanieAES_button.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.deszyfrowanieAES_button.setObjectName("deszyfrowanieAES_button")
        self.Szyfrowanie.addTab(self.tab_szyfrowanie, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Szyfrowanie.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "szyfrBox"))
        self.groupBox.setTitle(_translate("MainWindow", "Konto Dropbox"))
        self.pushButton.setText(_translate("MainWindow", "Autoryzuj"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Klucz"))
        self.labelKlucz.setText(_translate("MainWindow", "Twój klucz"))
        self.pushButton_2.setText(_translate("MainWindow", "Zapisz"))
        self.label_2.setText(_translate("MainWindow", "Odświeżanie"))
        self.Szyfrowanie.setTabText(self.Szyfrowanie.indexOf(self.tabDropbox), _translate("MainWindow", "Ustawienia konta"))
        self.label.setText(_translate("MainWindow", "Klucz"))
        self.pushButton_3.setText(_translate("MainWindow", "Zapisz"))
        self.AESGeneruj.setText(_translate("MainWindow", "AES Generuj"))
        self.KluczAES_line.setText(_translate("MainWindow", "KLUCZ AES"))
        self.Szyfrowanie.setTabText(self.Szyfrowanie.indexOf(self.tab_2), _translate("MainWindow", "Klucze"))
        self.email_box.setTitle(_translate("MainWindow", "GMAIL"))
        self.label_nadawca.setText(_translate("MainWindow", "           Nadawca"))
        self.label_haslo.setText(_translate("MainWindow", "                 Haslo"))
        self.label_adresat.setText(_translate("MainWindow", "             Adresat"))
        self.emailWyslij.setText(_translate("MainWindow", "Wyslij"))
        self.label_klucz.setText(_translate("MainWindow", "                  Klucz"))
        self.protokoly_box.setTitle(_translate("MainWindow", "Protokoly"))
        self.SSL_radio.setText(_translate("MainWindow", "SSL"))
        self.TSL_radio.setText(_translate("MainWindow", "TSL"))
        self.emailRSAGeneruj.setText(_translate("MainWindow", "RSA Generuj"))
        self.aesWyslij.setText(_translate("MainWindow", "Wyslij AES"))
        self.niezaszyfrowanyRSA.setText(_translate("MainWindow", "PLIK Z KLUCZEM PUBLICZNYM"))
        self.szyfrujRSA.setText(_translate("MainWindow", "Szyfruj RSA"))
        self.deszyfrujRSA.setText(_translate("MainWindow", "Deszyfruj RSA"))
        self.nazwaUzytkownikaLine.setText(_translate("MainWindow", "NAZWA UZYTKOWNIKA"))
        self.Szyfrowanie.setTabText(self.Szyfrowanie.indexOf(self.tab), _translate("MainWindow", "Wyślij klucz"))
        self.szyfrowanieAES_button.setText(_translate("MainWindow", "Szyfruj"))
        self.deszyfrowanieAES_button.setText(_translate("MainWindow", "Deszyfruj"))
        self.Szyfrowanie.setTabText(self.Szyfrowanie.indexOf(self.tab_szyfrowanie), _translate("MainWindow", "Szyfrowanie"))
